# This file contains all available configuration options
# with their default values.

version: "2"

# options for analysis running
run:

# output configuration options
output:
  formats:
    print-issued-lines: true
    colors: true

linters:
  settings:
    dupl:
      threshold: 200
    funlen:
      lines: 120
      statements: 120
    gocognit:
      min-complexity: 32
  enable:
    - bodyclose
    - dogsled
    - errcheck
#    - exportloopref  Depricated linter
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
#    - gofmt  moved to formatters
#    - goimports  moved to formatters
    - gosec
#    - gosimple  merged inside staticcheck
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
#    - stylecheck  merged inside staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)_test.go
        linters:
          - funlen
          - gocritic
          - gocognit

formatters:
  enable:
    - gofmt
    - goimports

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
